<style type="text/css">
	select.icon option{font-family: "fontAwesome"}
</style>
<select class="icon">
	<optgroup label="Web Application Icons">
		<option name="fonticon" value="icon-adjust" icon="fa-adjust"><i class="fa fa-adjust" aria-hidden="true"></i>&#xf042</option>
		<option name="fonticon" value="icon-asterisk"><i class="fa fa-asterisk"></i>a</option>
		<option name="fonticon" value="icon-ban-circle"><i class="fa fa-ban-circle"></i>a</option>
		<option name="fonticon" value="icon-bar-chart"><i class="fa fa-bar-chart"></i>a</option>
		<option name="fonticon" value="icon-barcode"><i class="fa fa-barcode"></i>a</option>
		<option name="fonticon" value="icon-beaker"><i class="fa fa-beaker"></i>a</option>
		<option name="fonticon" value="icon-beer"><i class="fa fa-beer"></i>a</option>
		<option name="fonticon" value="icon-bell"><i class="fa fa-bell"></i>a</option>
		<option name="fonticon" value="icon-bell-alt"><i class="fa fa-bell-alt"></i>a</option>
		<option name="fonticon" value="icon-bolt"><i class="fa fa-bolt"></i>a</option>
		<option name="fonticon" value="icon-book"><i class="fa fa-book"></i>a</option>
		<option name="fonticon" value="icon-bookmark"><i class="fa fa-bookmark"></i>a</option>
		<option name="fonticon" value="icon-bookmark-empty"><i class="fa fa-bookmark-empty"></i>a</option>
		<option name="fonticon" value="icon-briefcase"><i class="fa fa-briefcase"></i>a</option>
		<option name="fonticon" value="icon-bullhorn"><i class="fa fa-bullhorn"></i>a</option>
		<option name="fonticon" value="icon-calendar"><i class="fa fa-calendar"></i>a</option>
		<option name="fonticon" value="icon-camera"><i class="fa fa-camera"></i>a</option>
		<option name="fonticon" value="icon-camera-retro"><i class="fa fa-camera-retro"></i>a</option>
		<option name="fonticon" value="icon-certificate"><i class="fa fa-certificate"></i>a</option>
		<option name="fonticon" value="icon-check"><i class="fa fa-check"></i>a</option>
		<option name="fonticon" value="icon-check-empty"><i class="fa fa-check-empty"></i>a</option>
		<option name="fonticon" value="icon-circle"><i class="fa fa-circle"></i>a</option>
		<option name="fonticon" value="icon-circle-blank"><i class="fa fa-circle-blank"></i>a</option>
		<option name="fonticon" value="icon-cloud"><i class="fa fa-cloud"></i>a</option>
		<option name="fonticon" value="icon-cloud-download"><i class="fa fa-cloud-download"></i>a</option>
		<option name="fonticon" value="icon-cloud-upload"><i class="fa fa-cloud-upload"></i>a</option>
		<option name="fonticon" value="icon-coffee"><i class="fa fa-coffee"></i>a</option>
		<option name="fonticon" value="icon-cog"><i class="fa fa-cog"></i>a</option>
		<option name="fonticon" value="icon-cogs"><i class="fa fa-cogs"></i>a</option>
		<option name="fonticon" value="icon-comment"><i class="fa fa-comment"></i>a</option>
		<option name="fonticon" value="icon-comment-alt"><i class="fa fa-comment-alt"></i>a</option>
		<option name="fonticon" value="icon-comments"><i class="fa fa-comments"></i>a</option>
		<option name="fonticon" value="icon-comments-alt"><i class="fa fa-comments-alt"></i>a</option>
		<option name="fonticon" value="icon-credit-card"><i class="fa fa-credit-card"></i>a</option>
		<option name="fonticon" value="icon-dashboard"><i class="fa fa-dashboard"></i>a</option>
		<option name="fonticon" value="icon-desktop"><i class="fa fa-desktop"></i>a</option>
		<option name="fonticon" value="icon-download"><i class="fa fa-download"></i>a</option>
		<option name="fonticon" value="icon-download-alt"><i class="fa fa-download-alt"></i>a</option>
		<option name="fonticon" value="icon-edit"><i class="fa fa-edit"></i>a</option>
		<option name="fonticon" value="icon-envelope"><i class="fa fa-envelope"></i>a</option>
		<option name="fonticon" value="icon-envelope-alt"><i class="fa fa-envelope-alt"></i>a</option>
		<option name="fonticon" value="icon-exchange"><i class="fa fa-exchange"></i>a</option>
		<option name="fonticon" value="icon-exclamation-sign"><i class="fa fa-exclamation-sign"></i>a</option>
		<option name="fonticon" value="icon-external-link"><i class="fa fa-external-link"></i>a</option>
		<option name="fonticon" value="icon-eye-close"><i class="fa fa-eye-close"></i>a</option>
		<option name="fonticon" value="icon-eye-open"><i class="fa fa-eye-open"></i>a</option>
		<option name="fonticon" value="icon-facetime-video"><i class="fa fa-facetime-video"></i>a</option>
		<option name="fonticon" value="icon-fighter-jet"><i class="fa fa-fighter-jet"></i>a</option>
		<option name="fonticon" value="icon-film"><i class="fa fa-film"></i>a</option>
		<option name="fonticon" value="icon-filter"><i class="fa fa-filter"></i>a</option>
		<option name="fonticon" value="icon-fire"><i class="fa fa-fire"></i>a</option>
		<option name="fonticon" value="icon-flag"><i class="fa fa-flag"></i>a</option>
		<option name="fonticon" value="icon-folder-close"><i class="fa fa-folder-close"></i>a</option>
		<option name="fonticon" value="icon-folder-open"><i class="fa fa-folder-open"></i>a</option>
		<option name="fonticon" value="icon-folder-close-alt"><i class="fa fa-folder-close-alt"></i>a</option>
		<option name="fonticon" value="icon-folder-open-alt"><i class="fa fa-folder-open-alt"></i>a</option>
		<option name="fonticon" value="icon-food"><i class="fa fa-food"></i>a</option>
		<option name="fonticon" value="icon-gift"><i class="fa fa-gift"></i>a</option>
		<option name="fonticon" value="icon-glass"><i class="fa fa-glass"></i>a</option>
		<option name="fonticon" value="icon-globe"><i class="fa fa-globe"></i>a</option>
		<option name="fonticon" value="icon-group"><i class="fa fa-group"></i>a</option>
		<option name="fonticon" value="icon-hdd"><i class="fa fa-hdd"></i>a</option>
		<option name="fonticon" value="icon-headphones"><i class="fa fa-headphones"></i>a</option>
		<option name="fonticon" value="icon-heart"><i class="fa fa-heart"></i>a</option>
		<option name="fonticon" value="icon-heart-empty"><i class="fa fa-heart-empty"></i>a</option>
		<option name="fonticon" value="icon-home"><i class="fa fa-home"></i>a</option>
		<option name="fonticon" value="icon-inbox"><i class="fa fa-inbox"></i>a</option>
		<option name="fonticon" value="icon-info-sign"><i class="fa fa-info-sign"></i>a</option>
		<option name="fonticon" value="icon-key"><i class="fa fa-key"></i>a</option>
		<option name="fonticon" value="icon-leaf"><i class="fa fa-leaf"></i>a</option>
		<option name="fonticon" value="icon-laptop"><i class="fa fa-laptop"></i>a</option>
		<option name="fonticon" value="icon-legal"><i class="fa fa-legal"></i>a</option>
		<option name="fonticon" value="icon-lemon"><i class="fa fa-lemon"></i>a</option>
		<option name="fonticon" value="icon-lightbulb"><i class="fa fa-lightbulb"></i>a</option>
		<option name="fonticon" value="icon-lock"><i class="fa fa-lock"></i>a</option>
		<option name="fonticon" value="icon-unlock"><i class="fa fa-unlock"></i>a</option>
		<option name="fonticon" value="icon-magic"><i class="fa fa-magic"></i>a</option>
		<option name="fonticon" value="icon-magnet"><i class="fa fa-magnet"></i>a</option>
		<option name="fonticon" value="icon-map-marker"><i class="fa fa-map-marker"></i>a</option>
		<option name="fonticon" value="icon-minus"><i class="fa fa-minus"></i>a</option>
		<option name="fonticon" value="icon-minus-sign"><i class="fa fa-minus-sign"></i>a</option>
		<option name="fonticon" value="icon-mobile-phone"><i class="fa fa-mobile-phone"></i>a</option>
		<option name="fonticon" value="icon-money"><i class="fa fa-money"></i>a</option>
		<option name="fonticon" value="icon-move"><i class="fa fa-move"></i>a</option>
		<option name="fonticon" value="icon-music"><i class="fa fa-music"></i>a</option>
		<option name="fonticon" value="icon-off"><i class="fa fa-off"></i>a</option>
		<option name="fonticon" value="icon-ok"><i class="fa fa-ok"></i>a</option>
		<option name="fonticon" value="icon-ok-circle"><i class="fa fa-ok-circle"></i>a</option>
		<option name="fonticon" value="icon-ok-sign"><i class="fa fa-ok-sign"></i>a</option>
		<option name="fonticon" value="icon-pencil"><i class="fa fa-pencil"></i>a</option>
		<option name="fonticon" value="icon-picture"><i class="fa fa-picture"></i>a</option>
		<option name="fonticon" value="icon-plane"><i class="fa fa-plane"></i>a</option>
		<option name="fonticon" value="icon-plus"><i class="fa fa-plus"></i>a</option>
		<option name="fonticon" value="icon-plus-sign"><i class="fa fa-plus-sign"></i>a</option>
		<option name="fonticon" value="icon-print"><i class="fa fa-print"></i>a</option>
		<option name="fonticon" value="icon-pushpin"><i class="fa fa-pushpin"></i>a</option>
		<option name="fonticon" value="icon-qrcode"><i class="fa fa-qrcode"></i>a</option>
		<option name="fonticon" value="icon-question-sign"><i class="fa fa-question-sign"></i>a</option>
		<option name="fonticon" value="icon-quote-left"><i class="fa fa-quote-left"></i>a</option>
		<option name="fonticon" value="icon-quote-right"><i class="fa fa-quote-right"></i>a</option>
		<option name="fonticon" value="icon-random"><i class="fa fa-random"></i>a</option>
		<option name="fonticon" value="icon-refresh"><i class="fa fa-refresh"></i>a</option>
		<option name="fonticon" value="icon-remove"><i class="fa fa-remove"></i>a</option>
		<option name="fonticon" value="icon-remove-circle"><i class="fa fa-remove-circle"></i>a</option>
		<option name="fonticon" value="icon-remove-sign"><i class="fa fa-remove-sign"></i>a</option>
		<option name="fonticon" value="icon-reorder"><i class="fa fa-reorder"></i>a</option>
		<option name="fonticon" value="icon-reply"><i class="fa fa-reply"></i>a</option>
		<option name="fonticon" value="icon-resize-horizontal"><i class="fa fa-resize-horizontal"></i>a</option>
		<option name="fonticon" value="icon-resize-vertical"><i class="fa fa-resize-vertical"></i>a</option>
		<option name="fonticon" value="icon-retweet"><i class="fa fa-retweet"></i>a</option>
		<option name="fonticon" value="icon-road"><i class="fa fa-road"></i>a</option>
		<option name="fonticon" value="icon-rss"><i class="fa fa-rss"></i>a</option>
		<option name="fonticon" value="icon-screenshot"><i class="fa fa-screenshot"></i>a</option>
		<option name="fonticon" value="icon-search"><i class="fa fa-search"></i>a</option>
		<option name="fonticon" value="icon-share"><i class="fa fa-share"></i>a</option>
		<option name="fonticon" value="icon-share-alt"><i class="fa fa-share-alt"></i>a</option>
		<option name="fonticon" value="icon-shopping-cart"><i class="fa fa-shopping-cart"></i>a</option>
		<option name="fonticon" value="icon-signal"><i class="fa fa-signal"></i>a</option>
		<option name="fonticon" value="icon-signin"><i class="fa fa-signin"></i>a</option>
		<option name="fonticon" value="icon-signout"><i class="fa fa-signout"></i>a</option>
		<option name="fonticon" value="icon-sitemap"><i class="fa fa-sitemap"></i>a</option>
		<option name="fonticon" value="icon-sort"><i class="fa fa-sort"></i>a</option>
		<option name="fonticon" value="icon-sort-down"><i class="fa fa-sort-down"></i>a</option>
		<option name="fonticon" value="icon-sort-up"><i class="fa fa-sort-up"></i>a</option>
		<option name="fonticon" value="icon-spinner"><i class="fa fa-spinner"></i>a</option>
		<option name="fonticon" value="icon-star"><i class="fa fa-star"></i>a</option>
		<option name="fonticon" value="icon-star-empty"><i class="fa fa-star-empty"></i>a</option>
		<option name="fonticon" value="icon-star-half"><i class="fa fa-star-half"></i>a</option>
		<option name="fonticon" value="icon-tablet"><i class="fa fa-tablet"></i>a</option>
		<option name="fonticon" value="icon-tag"><i class="fa fa-tag"></i>a</option>
		<option name="fonticon" value="icon-tags"><i class="fa fa-tags"></i>a</option>
		<option name="fonticon" value="icon-tasks"><i class="fa fa-tasks"></i>a</option>
		<option name="fonticon" value="icon-thumbs-down"><i class="fa fa-thumbs-down"></i>a</option>
		<option name="fonticon" value="icon-thumbs-up"><i class="fa fa-thumbs-up"></i>a</option>
		<option name="fonticon" value="icon-time"><i class="fa fa-time"></i>a</option>
		<option name="fonticon" value="icon-tint"><i class="fa fa-tint"></i>a</option>
		<option name="fonticon" value="icon-trash"><i class="fa fa-trash"></i>a</option>
		<option name="fonticon" value="icon-trophy"><i class="fa fa-trophy"></i>a</option>
		<option name="fonticon" value="icon-truck"><i class="fa fa-truck"></i>a</option>
		<option name="fonticon" value="icon-umbrella"><i class="fa fa-umbrella"></i>a</option>
		<option name="fonticon" value="icon-upload"><i class="fa fa-upload"></i>a</option>
		<option name="fonticon" value="icon-upload-alt"><i class="fa fa-upload-alt"></i>a</option>
		<option name="fonticon" value="icon-user"><i class="fa fa-user"></i>a</option>
		<option name="fonticon" value="icon-user-md"><i class="fa fa-user-md"></i>a</option>
		<option name="fonticon" value="icon-volume-off"><i class="fa fa-volume-off"></i>a</option>
		<option name="fonticon" value="icon-volume-down"><i class="fa fa-volume-down"></i>a</option>
		<option name="fonticon" value="icon-volume-up"><i class="fa fa-volume-up"></i>a</option>
		<option name="fonticon" value="icon-warning-sign"><i class="fa fa-warning-sign"></i>a</option>
		<option name="fonticon" value="icon-wrench"><i class="fa fa-wrench"></i>a</option>
		<option name="fonticon" value="icon-zoom-in"><i class="fa fa-zoom-in"></i>a</option>
		<option name="fonticon" value="icon-zoom-out"><i class="fa fa-zoom-out"></i>a</option>
	<optgroup label="Text Editor Icons">
		<option name="fonticon" value="icon-file"><i class="fa fa-file"></i>a</option>
		<option name="fonticon" value="icon-file-alt"><i class="fa fa-file-alt"></i>a</option>
		<option name="fonticon" value="icon-cut"><i class="fa fa-cut"></i>a</option>
		<option name="fonticon" value="icon-copy"><i class="fa fa-copy"></i>a</option>
		<option name="fonticon" value="icon-paste"><i class="fa fa-paste"></i>a</option>
		<option name="fonticon" value="icon-save"><i class="fa fa-save"></i>a</option>
		<option name="fonticon" value="icon-undo"><i class="fa fa-undo"></i>a</option>
		<option name="fonticon" value="icon-repeat"><i class="fa fa-repeat"></i>a</option>
		<option name="fonticon" value="icon-text-height"><i class="fa fa-text-height"></i>a</option>
		<option name="fonticon" value="icon-text-width"><i class="fa fa-text-width"></i>a</option>
		<option name="fonticon" value="icon-align-left"><i class="fa fa-align-left"></i>a</option>
		<option name="fonticon" value="icon-align-center"><i class="fa fa-align-center"></i>a</option>
		<option name="fonticon" value="icon-align-right"><i class="fa fa-align-right"></i>a</option>
		<option name="fonticon" value="icon-align-justify"><i class="fa fa-align-justify"></i>a</option>
		<option name="fonticon" value="icon-indent-left"><i class="fa fa-indent-left"></i>a</option>
		<option name="fonticon" value="icon-indent-right"><i class="fa fa-indent-right"></i>a</option>
		<option name="fonticon" value="icon-font"><i class="fa fa-font"></i>a</option>
		<option name="fonticon" value="icon-bold"><i class="fa fa-bold"></i>a</option>
		<option name="fonticon" value="icon-italic"><i class="fa fa-italic"></i>a</option>
		<option name="fonticon" value="icon-strikethrough"><i class="fa fa-strikethrough"></i>a</option>
		<option name="fonticon" value="icon-underline"><i class="fa fa-underline"></i>a</option>
		<option name="fonticon" value="icon-link"><i class="fa fa-link"></i>a</option>
		<option name="fonticon" value="icon-paper-clip"><i class="fa fa-paper-clip"></i>a</option>
		<option name="fonticon" value="icon-columns"><i class="fa fa-columns"></i>a</option>
		<option name="fonticon" value="icon-table"><i class="fa fa-table"></i>a</option>
		<option name="fonticon" value="icon-th-large"><i class="fa fa-th-large"></i>a</option>
		<option name="fonticon" value="icon-th"><i class="fa fa-th"></i>a</option>
		<option name="fonticon" value="icon-th-list"><i class="fa fa-th-list"></i>a</option>
		<option name="fonticon" value="icon-list"><i class="fa fa-list"></i>a</option>
		<option name="fonticon" value="icon-list-ol"><i class="fa fa-list-ol"></i>a</option>
		<option name="fonticon" value="icon-list-ul"><i class="fa fa-list-ul"></i>a</option>
		<option name="fonticon" value="icon-list-alt"><i class="fa fa-list-alt"></i>a</option>
	<optgroup label="Directional Icons">
		<option name="fonticon" value="icon-angle-left"><i class="fa fa-angle-left"></i>a</option>
		<option name="fonticon" value="icon-angle-right"><i class="fa fa-angle-right"></i>a</option>
		<option name="fonticon" value="icon-angle-up"><i class="fa fa-angle-up"></i>a</option>
		<option name="fonticon" value="icon-angle-down"><i class="fa fa-angle-down"></i>a</option>
		<option name="fonticon" value="icon-arrow-down"><i class="fa fa-arrow-down"></i>a</option>
		<option name="fonticon" value="icon-arrow-left"><i class="fa fa-arrow-left"></i>a</option>
		<option name="fonticon" value="icon-arrow-right"><i class="fa fa-arrow-right"></i>a</option>
		<option name="fonticon" value="icon-arrow-up"><i class="fa fa-arrow-up"></i>a</option>
		<option name="fonticon" value="icon-caret-down"><i class="fa fa-caret-down"></i>a</option>
		<option name="fonticon" value="icon-caret-left"><i class="fa fa-caret-left"></i>a</option>
		<option name="fonticon" value="icon-caret-right"><i class="fa fa-caret-right"></i>a</option>
		<option name="fonticon" value="icon-caret-up"><i class="fa fa-caret-up"></i>a</option>
		<option name="fonticon" value="icon-chevron-down"><i class="fa fa-chevron-down"></i>a</option>
		<option name="fonticon" value="icon-chevron-left"><i class="fa fa-chevron-left"></i>a</option>
		<option name="fonticon" value="icon-chevron-right"><i class="fa fa-chevron-right"></i>a</option>
		<option name="fonticon" value="icon-chevron-up"><i class="fa fa-chevron-up"></i>a</option>
		<option name="fonticon" value="icon-circle-arrow-down"><i class="fa fa-circle-arrow-down"></i>a</option>
		<option name="fonticon" value="icon-circle-arrow-left"><i class="fa fa-circle-arrow-left"></i>a</option>
		<option name="fonticon" value="icon-circle-arrow-right"><i class="fa fa-circle-arrow-right"></i>a</option>
		<option name="fonticon" value="icon-circle-arrow-up"><i class="fa fa-circle-arrow-up"></i>a</option>
		<option name="fonticon" value="icon-double-angle-left"><i class="fa fa-double-angle-left"></i>a</option>
		<option name="fonticon" value="icon-double-angle-right"><i class="fa fa-double-angle-right"></i>a</option>
		<option name="fonticon" value="icon-double-angle-up"><i class="fa fa-double-angle-up"></i>a</option>
		<option name="fonticon" value="icon-double-angle-down"><i class="fa fa-double-angle-down"></i>a</option>
		<option name="fonticon" value="icon-hand-down"><i class="fa fa-hand-down"></i>a</option>
		<option name="fonticon" value="icon-hand-left"><i class="fa fa-hand-left"></i>a</option>
		<option name="fonticon" value="icon-hand-right"><i class="fa fa-hand-right"></i>a</option>
		<option name="fonticon" value="icon-hand-up"><i class="fa fa-hand-up"></i>a</option>
		<option name="fonticon" value="icon-circle"><i class="fa fa-circle"></i>a</option>
		<option name="fonticon" value="icon-circle-blank"><i class="fa fa-circle-blank"></i>a</option>
	<optgroup label="Video Player Icons">
		<option name="fonticon" value="icon-play-circle"><i class="fa fa-play-circle"></i>a</option>
		<option name="fonticon" value="icon-play"><i class="fa fa-play"></i>a</option>
		<option name="fonticon" value="icon-pause"><i class="fa fa-pause"></i>a</option>
		<option name="fonticon" value="icon-stop"><i class="fa fa-stop"></i>a</option>
		<option name="fonticon" value="icon-step-backward"><i class="fa fa-step-backward"></i>a</option>
		<option name="fonticon" value="icon-fast-backward"><i class="fa fa-fast-backward"></i>a</option>
		<option name="fonticon" value="icon-backward"><i class="fa fa-backward"></i>a</option>
		<option name="fonticon" value="icon-forward"><i class="fa fa-forward"></i>a</option>
		<option name="fonticon" value="icon-fast-forward"><i class="fa fa-fast-forward"></i>a</option>
		<option name="fonticon" value="icon-step-forward"><i class="fa fa-step-forward"></i>a</option>
		<option name="fonticon" value="icon-eject"><i class="fa fa-eject"></i>a</option>
		<option name="fonticon" value="icon-fullscreen"><i class="fa fa-fullscreen"></i>a</option>
		<option name="fonticon" value="icon-resize-full"><i class="fa fa-resize-full"></i>a</option>
		<option name="fonticon" value="icon-resize-small"><i class="fa fa-resize-small"></i>a</option>
	<optgroup label="Social Icons">
		<option name="fonticon" value="icon-phone"><i class="fa fa-phone"></i>a</option>
		<option name="fonticon" value="icon-phone-sign"><i class="fa fa-phone-sign"></i>a</option>
		<option name="fonticon" value="icon-facebook"><i class="fa fa-facebook"></i>a</option>
		<option name="fonticon" value="icon-facebook-sign"><i class="fa fa-facebook-sign"></i>a</option>
		<option name="fonticon" value="icon-twitter"><i class="fa fa-twitter"></i>a</option>
		<option name="fonticon" value="icon-twitter-sign"><i class="fa fa-twitter-sign"></i>a</option>
		<option name="fonticon" value="icon-github"><i class="fa fa-github"></i>a</option>
		<option name="fonticon" value="icon-github-alt"><i class="fa fa-github-alt"></i>a</option>
		<option name="fonticon" value="icon-github-sign"><i class="fa fa-github-sign"></i>a</option>
		<option name="fonticon" value="icon-linkedin"><i class="fa fa-linkedin"></i>a</option>
		<option name="fonticon" value="icon-linkedin-sign"><i class="fa fa-linkedin-sign"></i>a</option>
		<option name="fonticon" value="icon-pinterest"><i class="fa fa-pinterest"></i>a</option>
		<option name="fonticon" value="icon-pinterest-sign"><i class="fa fa-pinterest-sign"></i>a</option>
		<option name="fonticon" value="icon-google-plus"><i class="fa fa-google-plus"></i>a</option>
		<option name="fonticon" value="icon-google-plus-sign"><i class="fa fa-google-plus-sign"></i>a</option>
		<option name="fonticon" value="icon-sign-blank"><i class="fa fa-sign-blank"></i>a</option>
	<optgroup label="Medical Icons">
		<option name="fonticon" value="icon-ambulance"><i class="fa fa-ambulance"></i>a</option>
		<option name="fonticon" value="icon-beaker"><i class="fa fa-beaker"></i>a</option>
		<option name="fonticon" value="icon-h-sign"><i class="fa fa-h-sign"></i>a</option>
		<option name="fonticon" value="icon-hospital"><i class="fa fa-hospital"></i>a</option>
		<option name="fonticon" value="icon-medkit"><i class="fa fa-medkit"></i>a</option>
		<option name="fonticon" value="icon-plus-sign-alt"><i class="fa fa-plus-sign-alt"></i>a</option>
		<option name="fonticon" value="icon-stethoscope"><i class="fa fa-stethoscope"></i>a</option>
		<option name="fonticon" value="icon-user-md"><i class="fa fa-user-md"></i>a</option>
</select>